image:
  registry: docker.io
  repository: koenkk/zigbee2mqtt
  tag: "1.33.1"

# Node to run the pod on
nodeName: ""

config:
  permitJoin: false
  mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://mosquitto.mosquitto.svc.cluster.local
    username: "not_set"
    password: "not_set"
  devices: {}
  networkKey: |
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
