image:
  registry: docker.io
  repository: koenkk/zigbee2mqtt
  tag: "1.32.2"

# Node to run the pod on
nodeName: ""

config:
  permitJoin: false
  mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://mosquitto.mosquitto.svc.cluster.local
    username: "not_set"
    password: "not_set"
  devices: {}
